#version: "2.19.1"
#services:
#
#  # Publication:
#  #   container_name: publication
#  #   build: .\MSPublication-2
#  #   ports:
#  #     - "8082:8089"
#  #   hostname: publication
#  #   environment:
#  #     - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_2:3306/publicationDB?autoReconnect=true&useSSL=false
#  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
#  #   image: "publication"
#  #   depends_on:
#  #     - Eureka
#  #     - docker-mysql_2
#  
#  # Evenement:
#  #   container_name: evenement
#  #   build: .\ms_evenement
#  #   ports:
#  #     - "8080:8080"
#  #   hostname: evenement
#  #   environment:
#  #     - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_2:3306/evenementDB?autoReconnect=true&useSSL=false
#  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
#  #   image: "msevenement"
#  #   depends_on:
#  #     - Eureka
#  #     - docker-mysql_1
#  
#  # Page:
#  #   container_name: page
#  #   build: .\Page Microservice
#  #   ports:
#  #     - "8083:8083"
#  #   hostname: page
#  #   environment:
#  #     - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_2:3306/pageDB?autoReconnect=true&useSSL=false
#  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
#  #   image: "page"
#  #   depends_on:
#  #     - Eureka
#  #     - docker-mysql_3
#
#  # Commentaire:
#  #   container_name: commentaire
#  #   build: .\commentaire
#  #   ports:
#  #     - "8082:8760"
#  #   hostname: commentaire
#  #   environment:
#  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
#  #   image: "commentaire"
#  #   depends_on:
#  #     - Eureka
#
#  Groupe:
#    container_name: groupe-image
#    build: .\Groupe
#    ports:
#      - "8077:8077"
#    hostname: groupe
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
#    image: "groupe-img"
#    depends_on:
#      - Eureka
#
#  Eureka:
#    container_name: eureka
#    build: .\Eureka-Server
#    image: "eureka"
#    ports:
#      - "8761:8761"
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://Eureka:8761/eureka/
#
#  # docker-mysql_1:
#  #   image: "mysql:5.6"
#  #   environment:
#  #     - MYSQL_ROOT_PASSWORD=wacef
#  #     - MYSQL_DATABASE=evenementDB
#  #   ports:
#  #     - 3308:3306
#
#  # docker-mysql_2:
#  #   image: "mysql:5.6"
#  #   environment:
#  #     - MYSQL_ROOT_PASSWORD=root
#  #     - MYSQL_DATABASE=publicationDB
#  #   ports:
#  #     - 3307:3306
#
#  # docker-mysql_3:
#  #   image: "mysql:5.6"
#  #   environment:
#  #     - MYSQL_ROOT_PASSWORD=iheb
#  #     - MYSQL_DATABASE=pageDB
#  #   ports:
#  #     - 3308:3306

version: "2.19.1"
services:

  Groupe:
    container_name: groupe-image
    build: ./Groupe
    ports:
      - "8077:8077"
    hostname: groupe
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    image: "groupe-img"
    depends_on:
      - Eureka
    networks:
      - my-network

  Eureka:
    container_name: eureka
    build: ./Eureka-Server
    image: "eureka"
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - my-network

networks:
  my-network:
